/**
 * 通用组件合同领域错误定义与稳定错误码
 */

export type ComponentContractErrorCode =
  | "CONTRACT_VALIDATION_FAILED"
  | "INPUT_VALIDATION_FAILED"
  | "MATERIAL_REQUIREMENTS_UNMET"
  | "EXECUTION_PLAN_INVALID"
  | "OUTPUT_VALIDATION_FAILED"
  | "OUTPUT_KIND_NOT_SUPPORTED"
  | "MODEL_OUTPUT_INVALID"
  | "CONTRACT_LIFECYCLE_INVALID"
  | "UNKNOWN_INPUT_KIND"
  | "UNKNOWN_PIPELINE_STEP"
  | "UNKNOWN_MODEL_CAPABILITY"
  | "UNKNOWN_RENDERER_TYPE"
  | "FORBIDDEN_MODEL_BINDING"
  | "FORBIDDEN_EXECUTABLE_CODE"
  | "FORBIDDEN_SECRET_FIELD"
  | "UNSAFE_INTEGER_VALUE"
  | "CONTRACT_NOT_FOUND"
  | "DEFAULT_CONTRACT_FORBIDDEN"
  | "COST_PRICE_FALLBACK_FORBIDDEN"
  | "SCHEMA_KEYWORD_UNSUPPORTED"
  | "SCHEMA_TYPE_UNSUPPORTED"
  | "CITATIONS_STRUCTURE_REQUIRED"
  | "COMPONENT_NOT_FOUND"
  | "CONTRACT_VERSION_EXISTS"
  | "CONTRACT_IMMUTABLE"
  | "CONTRACT_IDENTITY_MISMATCH"
  | "CONTRACT_VERSION_MISMATCH"
  | "CONTRACT_ALREADY_PUBLISHED"
  | "CONTRACT_ALREADY_ARCHIVED"
  | "CONTRACT_ARCHIVED_CANNOT_PUBLISH"
  | "CONTRACT_ARCHIVED_CANNOT_EXECUTE"
  | "CONTRACT_DRAFT_CANNOT_EXECUTE"
  | "CONCURRENT_PUBLISH_CONFLICT"
  | "NO_PUBLISHED_CONTRACT"
  | "ACTIVE_CONTRACT_CANNOT_ARCHIVE"
  | "NO_ACTIVE_CONTRACT"
  | "COMPONENT_CONTRACT_NOT_READY"
  | "CONTRACT_NOT_PUBLISHED_CANNOT_ACTIVATE";

export class ComponentContractError extends Error {
  public readonly code: ComponentContractErrorCode;
  public readonly details?: unknown;

  constructor(code: ComponentContractErrorCode, message: string, details?: unknown) {
    super(`[COMPONENT_CONTRACT_ERROR][${code}] ${message}`);
    this.name = "ComponentContractError";
    this.code = code;
    this.details = details;
    Object.setPrototypeOf(this, ComponentContractError.prototype);
  }
}
