import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// 53 个核心组件完整数据 - 按 10 大软件工程阶段分组
const componentData = [
  // 第一阶段：商机捕获与售前打单
  {
    id: "C01",
    name: "标书智能解析",
    description: "提取标书关键条款，自动对比产品能力生成偏离表",
    type: "第一阶段：商机捕获与售前打单",
    category: "分析类",
    icon: "📄",
    tags: "标书，解析，偏离表",
    usageCount: 3421,
    sortOrder: 100,
    isPublished: true,
  },
  {
    id: "C02",
    name: "方案合规审查",
    description: "离线扫描技术方案，检查等保、国密等合规风险",
    type: "第一阶段：商机捕获与售前打单",
    category: "分析类",
    icon: "🛡️",
    tags: "合规，审查，等保，国密",
    usageCount: 2156,
    sortOrder: 99,
    isPublished: true,
  },
  {
    id: "C03",
    name: "竞品对比分析",
    description: "提取竞品文档核心数据，生成多维度对比矩阵",
    type: "第一阶段：商机捕获与售前打单",
    category: "分析类",
    icon: "⚔️",
    tags: "竞品，对比，分析",
    usageCount: 1876,
    sortOrder: 98,
    isPublished: true,
  },
  {
    id: "C04",
    name: "汇报话术转换",
    description: "根据汇报对象（高管/技术），自动调整技术方案的表达深度",
    type: "第一阶段：商机捕获与售前打单",
    category: "工具类",
    icon: "🗣️",
    tags: "汇报，话术，转换",
    usageCount: 2543,
    sortOrder: 97,
    isPublished: true,
  },
  {
    id: "C05",
    name: "项目成本测算",
    description: "结合历史数据推算项目隐性成本与预估毛利",
    type: "第一阶段：商机捕获与售前打单",
    category: "分析类",
    icon: "🧮",
    tags: "成本，测算，毛利",
    usageCount: 1234,
    sortOrder: 96,
    isPublished: true,
  },
  {
    id: "C06",
    name: "商业价值评估",
    description: "量化功能收益与开发成本，生成投入产出比报告",
    type: "第一阶段：商机捕获与售前打单",
    category: "分析类",
    icon: "📈",
    tags: "商业价值，评估，ROI",
    usageCount: 987,
    sortOrder: 95,
    isPublished: true,
  },
  // 第二阶段：需求定义与产品设计
  {
    id: "C07",
    name: "需求转 PRD",
    description: "将会议纪要或聊天记录，整理为结构化需求文档",
    type: "第二阶段：需求定义与产品设计",
    category: "生成类",
    icon: "🧩",
    tags: "需求，PRD，文档",
    usageCount: 4521,
    sortOrder: 94,
    isPublished: true,
  },
  {
    id: "C08",
    name: "异常场景补全",
    description: "根据主流程自动补充边界、并发等异常场景的处理建议",
    type: "第二阶段：需求定义与产品设计",
    category: "分析类",
    icon: "🕸️",
    tags: "异常场景，边界，并发",
    usageCount: 3245,
    sortOrder: 93,
    isPublished: true,
  },
  {
    id: "C09",
    name: "客诉归因分析",
    description: "聚类分析多渠道客诉数据，自动生成研发缺陷单",
    type: "第二阶段：需求定义与产品设计",
    category: "分析类",
    icon: "🎭",
    tags: "客诉，归因，缺陷",
    usageCount: 2876,
    sortOrder: 92,
    isPublished: true,
  },
  {
    id: "C10",
    name: "仿真数据生成",
    description: "依据真实行业规则，批量生成高逼真的业务测试数据",
    type: "第二阶段：需求定义与产品设计",
    category: "生成类",
    icon: "💉",
    tags: "仿真数据，测试数据",
    usageCount: 5432,
    sortOrder: 91,
    isPublished: true,
  },
  // 第三阶段：大前端与交互
  {
    id: "C11",
    name: "CSS 样式重构",
    description: "分析旧项目冗余样式，精简代码并提取设计规范 Token",
    type: "第三阶段：大前端与交互",
    category: "工具类",
    icon: "🧹",
    tags: "CSS，样式，重构",
    usageCount: 2134,
    sortOrder: 90,
    isPublished: true,
  },
  {
    id: "C12",
    name: "国际化词条校验",
    description: "检查多语言配置的完整性，智能翻译并预警 UI 文本截断",
    type: "第三阶段：大前端与交互",
    category: "工具类",
    icon: "🌐",
    tags: "国际化，多语言，翻译",
    usageCount: 1765,
    sortOrder: 89,
    isPublished: true,
  },
  {
    id: "C13",
    name: "页面合规检测",
    description: "扫描前端代码结构，输出无障碍访问及 SEO 优化建议",
    type: "第三阶段：大前端与交互",
    category: "分析类",
    icon: "♿",
    tags: "合规，无障碍，SEO",
    usageCount: 1432,
    sortOrder: 88,
    isPublished: true,
  },
  {
    id: "C14",
    name: "SVG 组件转换",
    description: "压缩图标体积，一键转换为可复用的前端代码组件",
    type: "第三阶段：大前端与交互",
    category: "工具类",
    icon: "🎨",
    tags: "SVG，图标，转换",
    usageCount: 2987,
    sortOrder: 87,
    isPublished: true,
  },
  {
    id: "C15",
    name: "设计稿转代码",
    description: "识别设计图布局，生成基础的 HTML5 与 CSS 结构",
    type: "第三阶段：大前端与交互",
    category: "生成类",
    icon: "📐",
    tags: "设计稿，代码生成，HTML,CSS",
    usageCount: 3654,
    sortOrder: 86,
    isPublished: true,
  },
  // 第四阶段：架构设计与 DBA
  {
    id: "C16",
    name: "数据库逆向解析",
    description: "扫描老旧数据库，自动生成 ER 关系图与数据字典",
    type: "第四阶段：架构设计与 DBA",
    category: "分析类",
    icon: "🗄️",
    tags: "数据库，逆向，ER 图",
    usageCount: 4123,
    sortOrder: 85,
    isPublished: true,
  },
  {
    id: "C17",
    name: "慢 SQL 优化",
    description: "分析数据库执行计划，提供索引建立与查询重写建议",
    type: "第四阶段：架构设计与 DBA",
    category: "工具类",
    icon: "🩺",
    tags: "SQL，优化，索引",
    usageCount: 3567,
    sortOrder: 84,
    isPublished: true,
  },
  {
    id: "C18",
    name: "微服务拆分建议",
    description: "基于表关联度与访问频率，自动推荐服务拆分边界",
    type: "第四阶段：架构设计与 DBA",
    category: "分析类",
    icon: "✂️",
    tags: "微服务，拆分，架构",
    usageCount: 2345,
    sortOrder: 83,
    isPublished: true,
  },
  {
    id: "C19",
    name: "数据迁移脚本",
    description: "跨数据库类型映射，生成数据清洗与迁移脚本",
    type: "第四阶段：架构设计与 DBA",
    category: "生成类",
    icon: "🚚",
    tags: "数据迁移，脚本，清洗",
    usageCount: 1876,
    sortOrder: 82,
    isPublished: true,
  },
  {
    id: "C20",
    name: "国产库语法转换",
    description: "将 Oracle 等传统 SQL 自动转换为达梦或人大金仓语法",
    type: "第四阶段：架构设计与 DBA",
    category: "工具类",
    icon: "🇨",
    tags: "国产库，语法转换，达梦",
    usageCount: 1234,
    sortOrder: 81,
    isPublished: true,
  },
  {
    id: "C21",
    name: "架构图代码生成",
    description: "根据自然语言描述，直接生成 Mermaid 架构和时序图代码",
    type: "第四阶段：架构设计与 DBA",
    category: "生成类",
    icon: "📊",
    tags: "架构图，Mermaid，代码生成",
    usageCount: 2987,
    sortOrder: 80,
    isPublished: true,
  },
  // 第五阶段：后端研发与 API
  {
    id: "C22",
    name: "生产数据脱敏",
    description: "对导出的生产数据进行掩码处理，保障测试环境隐私安全",
    type: "第五阶段：后端研发与 API",
    category: "工具类",
    icon: "🔒",
    tags: "数据脱敏，隐私，安全",
    usageCount: 3421,
    sortOrder: 79,
    isPublished: true,
  },
  {
    id: "C23",
    name: "接口文档逆向",
    description: "扫描后端源码，反向生成标准 OpenAPI/Swagger 文档",
    type: "第五阶段：后端研发与 API",
    category: "生成类",
    icon: "📡",
    tags: "接口文档，OpenAPI,Swagger",
    usageCount: 2654,
    sortOrder: 78,
    isPublished: true,
  },
  {
    id: "C24",
    name: "JSON 转实体类",
    description: "粘贴 JSON 报文，一键生成 Java/Go/TS 等强类型实体代码",
    type: "第五阶段：后端研发与 API",
    category: "工具类",
    icon: "🧱",
    tags: "JSON，实体类，代码生成",
    usageCount: 4532,
    sortOrder: 77,
    isPublished: true,
  },
  {
    id: "C25",
    name: "接口参数映射",
    description: "推理无文档 API 的参数含义，生成字段映射表与测试脚本",
    type: "第五阶段：后端研发与 API",
    category: "分析类",
    icon: "🔌",
    tags: "接口参数，映射，测试",
    usageCount: 1987,
    sortOrder: 76,
    isPublished: true,
  },
  {
    id: "C26",
    name: "正则表达式解析",
    description: "将复杂正则翻译为自然语言和图表，检测回溯性能风险",
    type: "第五阶段：后端研发与 API",
    category: "工具类",
    icon: "🔍",
    tags: "正则表达式，解析，性能",
    usageCount: 1543,
    sortOrder: 75,
    isPublished: true,
  },
  {
    id: "C27",
    name: "硬件错误码诊断",
    description: "匹配设备厂商错误码库，直接给出硬件或 SDK 报错原因",
    type: "第五阶段：后端研发与 API",
    category: "分析类",
    icon: "💊",
    tags: "错误码，诊断，硬件",
    usageCount: 2876,
    sortOrder: 74,
    isPublished: true,
  },
  // 第六阶段：质量保证 QA
  {
    id: "C28",
    name: "测试用例生成",
    description: "解析需求文档，自动生成涵盖正逆向与边界的用例表",
    type: "第六阶段：质量保证 QA",
    category: "生成类",
    icon: "🧪",
    tags: "测试用例，生成，QA",
    usageCount: 3765,
    sortOrder: 73,
    isPublished: true,
  },
  {
    id: "C29",
    name: "漏洞 Payload 构造",
    description: "批量生成用于安全测试的注入、越权及超长脏数据",
    type: "第六阶段：质量保证 QA",
    category: "工具类",
    icon: "☢️",
    tags: "漏洞，Payload，安全测试",
    usageCount: 2134,
    sortOrder: 72,
    isPublished: true,
  },
  {
    id: "C30",
    name: "缺陷单自动完善",
    description: "识别报错截图，自动补全复现步骤与环境前置条件",
    type: "第六阶段：质量保证 QA",
    category: "工具类",
    icon: "📸",
    tags: "缺陷单，截图，复现",
    usageCount: 2987,
    sortOrder: 71,
    isPublished: true,
  },
  {
    id: "C31",
    name: "压测脚本与分析",
    description: "根据性能指标生成 JMeter 脚本，并解析测试报告瓶颈",
    type: "第六阶段：质量保证 QA",
    category: "工具类",
    icon: "📈",
    tags: "压测，JMeter，性能分析",
    usageCount: 1876,
    sortOrder: 70,
    isPublished: true,
  },
  {
    id: "C32",
    name: "UI 自动化修复",
    description: "对比前端 DOM 变更，批量修复失效的测试选择器",
    type: "第六阶段：质量保证 QA",
    category: "工具类",
    icon: "🩹",
    tags: "UI 自动化，修复，测试",
    usageCount: 2345,
    sortOrder: 69,
    isPublished: true,
  },
  // 第七阶段：DevOps 与运维
  {
    id: "C33",
    name: "报错日志根因分析",
    description: "过滤海量日志，聚合报错堆栈并定位故障根本原因",
    type: "第七阶段：DevOps 与运维",
    category: "分析类",
    icon: "⚡",
    tags: "日志分析，根因，故障",
    usageCount: 4321,
    sortOrder: 68,
    isPublished: true,
  },
  {
    id: "C34",
    name: "云资源降本优化",
    description: "识别闲置云资源，一键生成资源释放或降配脚本",
    type: "第七阶段：DevOps 与运维",
    category: "工具类",
    icon: "💸",
    tags: "云资源，降本，优化",
    usageCount: 1654,
    sortOrder: 67,
    isPublished: true,
  },
  {
    id: "C35",
    name: "开源合规审计",
    description: "扫描代码依赖树，预警 GPL 等传染性开源协议风险",
    type: "第七阶段：DevOps 与运维",
    category: "分析类",
    icon: "⚖️",
    tags: "开源协议，合规，GPL",
    usageCount: 2123,
    sortOrder: 66,
    isPublished: true,
  },
  {
    id: "C36",
    name: "漏扫报告转化",
    description: "将第三方安全扫描报告，转化为开发可直接执行的代码修复单",
    type: "第七阶段：DevOps 与运维",
    category: "工具类",
    icon: "🛡️",
    tags: "漏扫，安全，修复",
    usageCount: 2876,
    sortOrder: 65,
    isPublished: true,
  },
  {
    id: "C37",
    name: "配置文件检查",
    description: "校验 Nginx/K8s 配置的逻辑冲突，预防发布事故",
    type: "第七阶段：DevOps 与运维",
    category: "工具类",
    icon: "🚥",
    tags: "配置文件，Nginx,K8s",
    usageCount: 1987,
    sortOrder: 64,
    isPublished: true,
  },
  {
    id: "C38",
    name: "容器镜像瘦身",
    description: "优化 Dockerfile 构建步骤，清理冗余依赖以压缩镜像体积",
    type: "第七阶段：DevOps 与运维",
    category: "工具类",
    icon: "🐳",
    tags: "容器，Docker，镜像优化",
    usageCount: 3245,
    sortOrder: 63,
    isPublished: true,
  },
  // 第八阶段：交付实施与协同
  {
    id: "C39",
    name: "项目汇报美化",
    description: "润色项目延期或技术阻碍等敏感汇报的语言表达",
    type: "第八阶段：交付实施与协同",
    category: "工具类",
    icon: "👔",
    tags: "汇报，润色，表达",
    usageCount: 2654,
    sortOrder: 62,
    isPublished: true,
  },
  {
    id: "C40",
    name: "硬件日志诊断",
    description: "解析非标准设备日志，辅助软硬件联调排障",
    type: "第八阶段：交付实施与协同",
    category: "分析类",
    icon: "🔌",
    tags: "硬件日志，诊断，联调",
    usageCount: 1876,
    sortOrder: 61,
    isPublished: true,
  },
  {
    id: "C41",
    name: "验收单据生成",
    description: "提取往来邮件记录，批量生成符合甲方规范的验收确认单",
    type: "第八阶段：交付实施与协同",
    category: "生成类",
    icon: "✍️",
    tags: "验收单，生成，邮件",
    usageCount: 1234,
    sortOrder: 60,
    isPublished: true,
  },
  {
    id: "C42",
    name: "操作手册生成",
    description: "识别系统截图交互点，自动生成图文并茂的用户使用手册",
    type: "第八阶段：交付实施与协同",
    category: "生成类",
    icon: "📚",
    tags: "操作手册，文档，截图",
    usageCount: 3421,
    sortOrder: 59,
    isPublished: true,
  },
  {
    id: "C43",
    name: "敏捷回顾总结",
    description: "过滤情绪化发言，从会议记录中提炼具体的改进任务",
    type: "第八阶段：交付实施与协同",
    category: "分析类",
    icon: "🧊",
    tags: "敏捷回顾，会议，改进",
    usageCount: 2134,
    sortOrder: 58,
    isPublished: true,
  },
  {
    id: "C44",
    name: "研发效能分析",
    description: "结合代码提交与工单数据，客观评估团队成员技术贡献度",
    type: "第八阶段：交付实施与协同",
    category: "分析类",
    icon: "🕵️",
    tags: "效能分析，评估，贡献度",
    usageCount: 1543,
    sortOrder: 57,
    isPublished: true,
  },
  {
    id: "C45",
    name: "团队知识库问答",
    description: "索引本地多格式文档，构建团队内部安全的知识问答助手",
    type: "第八阶段：交付实施与协同",
    category: "工具类",
    icon: "🧠",
    tags: "知识库，问答，文档",
    usageCount: 2987,
    sortOrder: 56,
    isPublished: true,
  },
  // 第九阶段：系统扩展底座
  {
    id: "C46",
    name: "多模型路由网关",
    description: "统一调度云端与本地大模型 API，实现负载均衡与计费控制",
    type: "第九阶段：系统扩展底座",
    category: "工具类",
    icon: "🔀",
    tags: "路由网关，模型，负载均衡",
    usageCount: 5432,
    sortOrder: 55,
    isPublished: true,
  },
  {
    id: "C47",
    name: "全局视觉内核",
    description: "统管平台设计规范，提供标准化前端 UI 组件库",
    type: "第九阶段：系统扩展底座",
    category: "工具类",
    icon: "💅",
    tags: "视觉规范，UI，组件库",
    usageCount: 4321,
    sortOrder: 54,
    isPublished: true,
  },
  {
    id: "C48",
    name: "工作流编排器",
    description: "可视化拖拽编排工具，支持多组件串联的复杂任务流",
    type: "第九阶段：系统扩展底座",
    category: "工具类",
    icon: "⚙️",
    tags: "工作流，编排，可视化",
    usageCount: 3654,
    sortOrder: 53,
    isPublished: true,
  },
  {
    id: "C49",
    name: "脚本 UI 化工具",
    description: "将命令行脚本一键封装为带交互界面的可执行桌面程序",
    type: "第九阶段：系统扩展底座",
    category: "工具类",
    icon: "🖥️",
    tags: "脚本，UI 化，桌面程序",
    usageCount: 2876,
    sortOrder: 52,
    isPublished: true,
  },
  {
    id: "C50",
    name: "本地向量数据库",
    description: "提供轻量级本地向量存储与检索，支持断网环境运作",
    type: "第九阶段：系统扩展底座",
    category: "工具类",
    icon: "🗃️",
    tags: "向量数据库，存储，检索",
    usageCount: 2134,
    sortOrder: 51,
    isPublished: true,
  },
  {
    id: "C51",
    name: "授权与计费中心",
    description: "管理组件调用配额，提供机器码绑定的本地防破解验证",
    type: "第九阶段：系统扩展底座",
    category: "工具类",
    icon: "💳",
    tags: "授权，计费，配额",
    usageCount: 1765,
    sortOrder: 50,
    isPublished: true,
  },
  {
    id: "C52",
    name: "沙箱隔离环境",
    description: "限制模型对本地文件的读写权限，确保数据处理绝对安全",
    type: "第九阶段：系统扩展底座",
    category: "工具类",
    icon: "🧫",
    tags: "沙箱，隔离，安全",
    usageCount: 2345,
    sortOrder: 49,
    isPublished: true,
  },
  // 第十阶段：交付与可视化
  {
    id: "C53",
    name: "架构可视化渲染",
    description: "将底层代码/文本，无缝渲染为标准交互式系统架构图与脑图",
    type: "第十阶段：交付与可视化",
    category: "生成类",
    icon: "🖼️",
    tags: "架构可视化，渲染，脑图",
    usageCount: 3987,
    sortOrder: 48,
    isPublished: true,
  },
];

async function main() {
  console.log("开始初始化 53 个组件数据...");

  let created = 0;
  let updated = 0;

  for (const component of componentData) {
    try {
      // 先尝试创建，如果存在则更新
      await prisma.componenttask.upsert({
        where: { id: component.id },
        update: {
          name: component.name,
          description: component.description,
          type: component.type,
          category: component.category,
          icon: component.icon,
          tags: component.tags,
          usageCount: component.usageCount,
          sortOrder: component.sortOrder,
          isPublished: component.isPublished,
        },
        create: {
          id: component.id,
          name: component.name,
          description: component.description,
          type: component.type,
          category: component.category,
          icon: component.icon,
          tags: component.tags,
          usageCount: component.usageCount,
          sortOrder: component.sortOrder,
          isPublished: component.isPublished,
          status: "published",
        },
      });
      
      created++;
      console.log(`✓ 组件 ${component.id} - ${component.name} 已准备就绪`);
    } catch (error) {
      console.error(`Failed to create/update component ${component.id}:`, error);
    }
  }

  console.log(`\n组件数据初始化完成！`);
  console.log(`创建/更新：${created} 个组件`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
